apiVersion: v1 
kind: Service 
metadata: 
name: docker-demo-app-service 
spec: 
selector: 
app: docker-demo-app 
ports: 
- protocol: "TCP" 
port: 8080 
targetPort: 8080 
type: LoadBalancer
---
apiVersion: apps/v1 
kind: Deployment 
metadata: 
name: docker-demo-app 
spec: 
selector: 
matchLabels: 
app: docker-demo-app 
replicas: 3 
template: 
metadata: 
labels: 
app: docker-demo-app 
spec: 
containers: 
- name: docker-demo-app 
image: larry1119/docker-demo-app:latest
imagePullPolicy: Always 
ports: 
- containerPort: 8080